//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_tbl
    {
        public string TaskId { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public string Status { get; set; }
        public string Content_task { get; set; }
    }
}
